default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: password

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: <%= ENV["RENDER_DB"] %>
  username: <%= ENV["RENDER_DB_USERNAME"] %>
  password: <%= ENV["RENDER_DB_PASSWORD"] %>